```{r}
library(tidyverse)
library(visdat)
library(skimr)
library(naniar)
library(here)
library(dplyr)
```

```{r}
data_raw = read_csv(here("data", "raw", "ICT_data_raw.csv"))
```

```{r}
data_clean = data_raw %>% select(
                       # Constant / metadata columns
                       -STRUCTURE,
                       -STRUCTURE_ID,
                       -STRUCTURE_NAME,
                       -ACTION,
                       -FREQ,
                       -`Frequency of observation`,
                       -GEO_AREA,
                       -`Geographical area`,
                       -`Unit multiplier`,
                       -UNIT_MULT,
                       -Decimals,
                       -DECIMALS,
                       
                       # Empty columns (no information)
                       -`Time period`,
                       -`Observation value`,
                       -OBS_STATUS_3,
                       -`Observation status 3`,
                       -TIME_HORIZON_USE,
                       -`Time horizon`,
                       
                       # Redundant label variables (coded versions kept). "Income group", "Employment status", and "V7 Breakdowns households" are deliberately kept because the corresponding coded versions are not clearly documented.
                       -Measure,
                       -`Reference area`,
                       -`Unit of measure`,
                       -Age,
                       -Sex,
                       -`Education level`,
                       -`Income group`,
                       -`Employment status`,

                        # Not used in analysis
                       -OBS_STATUS,
                       -`Observation status`,
                       -OBS_STATUS_2,
                       -`Observation status 2`,
                       )

#get all cols with _T
cols_with_T = data_clean %>%
  select(where(~ any(.x == "_T", na.rm = TRUE))) %>%
  names()

#replace _T with Total 
data_clean = data_clean %>%
  mutate (
    across(cols_with_T, ~ if_else(.x == "_T", "Total", .x))
  )

write_csv(
  data_clean,
  here("data", "processed", "ICT_data_clean.csv")
)
```

```{r}
skim(data_clean)
glimpse(data_clean)
vis_dat(data_clean)
```
